version: "3.9"

services:
  prometheus:
    build: 
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus/container_prometheus_data'
    volumes: 
      - prometheus_data:/etc/prometheus/container_prometheus_data
    restart: unless-stopped
    ports:
      - 9090:9090
    networks: 
      - monitoring_network
      - jenkins_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports: 
      - 3000:3000
    volumes: 
      - grafana-storage:/var/lib/grafana grafana/grafana
    networks: 
      - monitoring_network
      - jenkins_network

volumes: 
  prometheus_data:
  grafana-storage:

networks: 
  monitoring_network:
  jenkins_network: